version: "3.1"

services:
  hdpmst:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    volumes:
      - .:/root/staging
      - name0:/hadoop/hdfs/namenode
    networks:
      - mynet
    environment:
      - HADOOP_HOST_SLAVES=hdp1,hdp2,hdp3
    depends_on:
      - hdp1,hdp2,hdp3
  hdp1:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    volumes:
      - data1:/hadoop/hdfs/datanode
    networks:
      - mynet
  hdp2:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
    volumes:
      - data2:/hadoop/hdfs/datanode
    networks:
      - mynet
  hdp3:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp3
    volumes:
      - data3:/hadoop/hdfs/datanode
    networks:
      - mynet
#  hdp4:
#    image: mkenjis/ubhdpclu_vol_img
#    deploy:
#      placement:
#        constraints:
#          - node.labels.hostlabel == hdpmst
#    volumes:
#      - data4:/hadoop/hdfs/datanode
#    environment:
#      - HADOOP_MASTER=hdpmst
#    networks:
#      - mynet

networks:
  mynet:

volumes:
  name0:
  data1:
  data2:
  data3:
#  data4:
